CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_SILVER}.{TABLE_CLEANED}` 
PARTITION BY DATE(InvoiceDate)
CLUSTER BY Country AS
SELECT *
FROM `{PROJECT_ID}.{DATASET_BRONZE}.{TABLE_RAW}`
WHERE CustomerID IS NOT NULL AND Quantity > 0 AND UnitPrice > 0;